apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: skaffold-
build:
  artifacts:
  - image: alpine
    context: private-api
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
  - image: antgonto/kubelabs_privateapi_skaffold
    context: private-api
    docker:
      dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
    - private-api\kustomize\overlays\dev
profiles:
- name: base
  manifests:
    kustomize:
      paths:
      - private-api\kustomize\base
- name: stage
  manifests:
    kustomize:
      paths:
      - private-api\kustomize\overlays\stage
