apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: private-api
build:
  local:
    concurrency: 0 # Build all the images in the array
  tagPolicy:
  #  envTemplate:
  #    template: "{{.APP_VERSION}}"
  # ---
 #   gitCommit:
 #     variant: AbbrevCommitSha
 #     prefix:  "api-"
    customTemplate:
      template: "{{.PREF}}_{{.SUFF}}"
      components:
        - name: PREF
          dateTime:
            format: "2006-01-02"
            timezone: "Local"
        - name: SUFF
          gitCommit:
            variant: AbbrevCommitSha
            prefix: "api_"
  artifacts:
  - image: skaffold
    docker:
      dockerfile: Dockerfile
#      buildArgs:
#        APP_ENV: "{{.APP_ENV_DEV}}"
manifests:
 rawYaml:
   - kube/ns.yaml
   - kube/deploy.yaml
   - kube/svc.yaml
profiles:
  - name: dev
#    patches:
#    - op: replace
#      path: /build/artifacts/0/docker/buildArgs/APP_ENV
#      value: "{{.APP_ENV_DEV}}"

    manifests:
      kustomize:
        paths:
          - kustomize/overlays/dev
#  - name: stage
    # activation:
    #  - kubeContext: docker-desktop
#    patches:
#    - op: replace
#      path: /build/artifacts/0/docker/buildArgs/APP_ENV
#      value: "{{.APP_ENV_DEV}}"
#    manifests:
#      kustomize:
#        paths:
#          - kustomize/overlays/stage
#      artifacts:
#      - image: antgonto/kubelabs_privateapi_skaffold
#        docker:
#          dockerfile: Dockerfile
#          buildArgs:
#            APP_ENV: "{{.APP_ENV_DEV}}"
  - name: stage
    build:
      artifacts:
      - image: antgonto/kubelabs_privateapi_skaffold
#        docker:
#          dockerfile: Dockerfile
#          buildArgs:
#            APP_ENV: "{{.APP_ENV_DEV}}"
